version: '3'

services:
  app:
    build: .
    container_name: go-server
    ports:
      - "8080:8080"   # Map container port 8080 to local port 8080
    environment:      # Environment variable for the app
      - PORT=8080  
      - HOST=0.0.0.0  # allows any host -> port forwarding, 127.0.0.1 doesn't work that way
    restart: unless-stopped